// Generated by CoffeeScript 1.10.0
(function() {
  var cc, dispatcher;

  cc = (function() {
    function cc(c, img) {
      this.c = c;
      this.ctx = c.getContext('2d');
      this.image = img;
    }

    cc.prototype.clear = function() {
      this.ctx.fillStyle = "#fff";
      return this.ctx.fillRect(0, 0, this.c.width, this.c.height);
    };

    cc.prototype.tile = function(tx, ty, cx, cy) {
      return this.ctx.drawImage(this.image, tx * 16, ty * 16, 16, 16, cx * 16, cy * 16, 16, 16);
    };

    return cc;

  })();

  dispatcher = new WebSocketRails('78.47.206.129/websocket');

  dispatcher.on_open = function(data) {
    console.log('Connection has been established');
    return $(function() {
      var ac, animtick, curPlayer, frame2, g_map, handlePlayer, move_channel, objectList, player_data, renderPlayers, sign_channel, t, uid, updateTile;
      objectList = {};
      g_map = null;
      ac = new cc(document.getElementById("canvas"), document.getElementById("tiles"));
      ac.clear();
      frame2 = true;
      updateTile = function(tile, pos) {
        if (frame2) {
          ac.tile(1, 0, pos.x, pos.y);
          return ac.tile(tile[0], tile[1], pos.x, pos.y);
        } else {
          ac.tile(1, 0, pos.x, pos.y);
          return ac.tile(tile[0] + 1, tile[1], pos.x, pos.y);
        }
      };
      sign_channel = dispatcher.subscribe('player');
      sign_channel.bind('signed_in', function(msg) {
        console.log("Player with id joined: " + msg.id);
        return console.log(msg);
      });
      move_channel = dispatcher.subscribe('player');
      move_channel.bind('move', function(msg) {
        console.log("Player with id moved: " + msg.id);
        console.log(msg);
        if (curPlayer.id === msg.id) {
          ac.tile(1, 0, curPlayer.pos.x, curPlayer.pos.y);
          curPlayer.pos = msg.pos;
          return renderPlayers();
        } else {
          return objectList[msg.id + ""] = msg;
        }
      });
      curPlayer = null;
      handlePlayer = function(ply) {
        console.log(ply);
        curPlayer = ply;
        dispatcher.trigger('level.get_map', {
          player_uid: curPlayer.uid
        }, function(map) {
          var i, j, x, y;
          g_map = map;
          for (x = i = 0; i <= 19; x = ++i) {
            for (y = j = 0; j <= 19; y = ++j) {
              if (map[x][y] === 1) {
                ac.tile(0, 0, x, y);
              }
              if (map[x][y] === 0) {
                ac.tile(1, 0, x, y);
              }
            }
          }
          return updateTile([8, 0], curPlayer.pos);
        });
        return dispatcher.trigger('level.get_players', {
          player_uid: curPlayer.uid
        }, function(players) {
          var i, len, x;
          console.log("Got players:");
          for (i = 0, len = players.length; i < len; i++) {
            x = players[i];
            objectList[x.id + ""] = x;
          }
          return console.log(objectList);
        });
      };
      if (uid = localStorage.getItem('player_uid')) {
        player_data = {
          uid: uid
        };
        dispatcher.trigger('player.sign_in', player_data, function(player) {
          console.log('existed user signed in');
          return handlePlayer(player);
        }, function(error_msg) {
          console.log('something wrong:');
          return console.log(error_msg);
        });
      } else {
        dispatcher.trigger('player.create', '', function(player) {
          console.log('new user created successfully');
          handlePlayer(player);
          return localStorage.setItem('player_uid', player.uid);
        }, function(error_msg) {
          console.log('User was not created by some reasons: ');
          return console.log(error_msg);
        });
      }
      renderPlayers = function() {
        var k, v;
        for (k in objectList) {
          v = objectList[k];
          updateTile([8, 1], v.pos);
        }
        return updateTile([8, 0], curPlayer.pos);
      };
      animtick = function() {
        var i, j, x, y;
        for (x = i = 0; i <= 19; x = ++i) {
          for (y = j = 0; j <= 19; y = ++j) {
            if (g_map[x][y] === 1) {
              ac.tile(0, 0, x, y);
            }
            if (g_map[x][y] === 0) {
              ac.tile(1, 0, x, y);
            }
          }
        }
        renderPlayers();
        return frame2 = !frame2;
      };
      setInterval(animtick, 500);
      t = 0;
      $(document).bind("keydown", function(e) {
        var dir, dirx, diry;
        dir = null;
        dirx = 0;
        diry = 0;
        if (e.keyCode === 37) {
          dir = "left";
        }
        if (e.keyCode === 38) {
          dir = "up";
        }
        if (e.keyCode === 39) {
          dir = "right";
        }
        if (e.keyCode === 40) {
          dir = "down";
        }
        if (dir) {
          e.preventDefault();
          if (t - new Date().getTime() < 0) {
            dispatcher.trigger('player.move', {
              player_uid: curPlayer.uid,
              direction: dir
            }, function(obj) {
              return console.log(obj);
            }, function(error_msg) {
              return console.log(error_msg);
            });
            return t = new Date().getTime() + 300;
          }
        }
      });
      return $('#reqmap').on('click', function() {
        return dispatcher.trigger('level.map', 'nothing', function(map) {
          var i, j, x, y;
          console.log(map);
          for (x = i = 0; i <= 19; x = ++i) {
            for (y = j = 0; j <= 19; y = ++j) {
              if (map[x][y] === 1) {
                ac.tile(0, 0, x, y);
              }
              if (map[x][y] === 0) {
                ac.tile(1, 0, x, y);
              }
            }
          }
          return $('#map').text("test");
        });
      });
    });
  };

}).call(this);
